POST http://localhost:9000/suppliers HTTP/1.1
content-type: application/json

{
    "name": "Tran Dang Tuan",
    "email": "Tuantd@gmail.com",
    "phoneNumber": "0905843460",
    "address": "38 Yen Bai"
}