POST  http://localhost:9000/customers HTTP/1.1
content-type: application/json


 {
    "firstName": "Tran ",
    "lastName":"Khach Hang7",
    "phoneNumber":"0931932039",
    "address":"38 Yen Bai",
    "email": "tuantd@gmail.com",
    "birthday":"2023-3-30"
  } 