POST http://localhost:9000/products HTTP/1.1
content-type: application/json

{
   "name": "Xe máy",
   "price": 100,
   "discount": 10,
   "stock": 90,
   "categoryId": "6426c8689dc8a88b63ba4f87",
   "supplierId": "6426c7f49dc8a88b63ba4f83"

}